apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- setup.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: rhoai-setup
    namespace: redhat-ods-operator
    files:
      - scripts/setup.sh
  - name: dependency-manifests
    namespace: redhat-ods-operator
    files:
      - scripts/dependency-manifests/serverless_operator_group.yaml
      - scripts/dependency-manifests/serverless_subscription.yaml
      - scripts/dependency-manifests/service_mesh_2_subscription.yaml
  - name: openshift-ai
    namespace: redhat-ods-operator
    files:
      - scripts/openshift-ai/operator_group.yaml
      - scripts/openshift-ai/subscription.yaml
  - name: datasciencecluster
    namespace: redhat-ods-operator
    files:
      - scripts/datasciencecluster/dsc.yaml
