---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhoai-setup
  namespace: redhat-ods-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhoai-setup
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
  - apiGroups:
      - operators.coreos.com
    resources:
      - operatorgroups
      - subscriptions
      - installplans
    verbs:
      - get
      - list
      - patch
      - create
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - delete
    resourceNames:
      - rhoai-setup
      - rhoai-manifests
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rhoai-setup
subjects:
  - kind: ServiceAccount
    name: rhoai-setup
    namespace: redhat-ods-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhoai-setup
---
apiVersion: batch/v1
kind: Job
metadata:
  name: rhoai-setup
  namespace: redhat-ods-operator
spec:
  template:
    spec:
      containers:
        - name: minion
          image: registry.redhat.io/openshift4/ose-cli
          command:
            - /bin/bash
            - -c
            - /scripts/setup.sh
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: manifests
              mountPath: /scripts/manifests
      volumes:
        - name: scripts
          configMap:
            name: rhoai-setup
            defaultMode: 0755
        - name: manifests
          configMap:
            name: rhoai-manifests
            defaultMode: 0755
      restartPolicy: Never
      serviceAccount: rhoai-setup
      serviceAccountName: rhoai-setup
  backoffLimit: 4